# Ejercicios de Numpy
Inteligencia Artificial - Facundo A. Lucianna - CEIA - FIUBA

A continuación veamos ejercicios de Numpy que deben resolver.

Ejercicio 1: Importa a Numpy como np

In [1]:
import numpy as np

Ejercicio 2: Crea un array de la siguiente lista

In [2]:
lista = [1, 2, 3, 4, 5]
arr = np.array(lista)
print(arr)

[1 2 3 4 5]


Ejercicio 3: Suma los siguientes dos arrays

In [3]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])


In [4]:
suma = a + b
print(suma)

[[11 13 15]
 [17 19 21]]


Ejercicio 4: Multiplica por 3.2 al siguiente array (una matriz)

In [5]:
a = np.array([[4,2,2],
              [4,1,0]])
producto = a * 3.2
print(producto)

[[12.8  6.4  6.4]
 [12.8  3.2  0. ]]


Ejercicio 5: Convierta en una matriz cuadrada al siguiente array unidimensional.

1. Usando shape fijate que dimension tiene el array
2. Usando .reshape() convierta al array en una matriz cuadrada


In [6]:
a = np.array([x for x in range(9)])
print("Dimension de a:", a.shape)
matriz = a.reshape(int(np.sqrt(len(a))),int(np.sqrt(len(a))))
print(matriz)

Dimension de a: (9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Ejercicio 6: Convierta el tipo del siguiente array en entero (int)

In [7]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

In [8]:
a_int = a.astype(int)
print(a_int)

[[2 3 1]
 [4 2 1]]


Ejercicio 7: Crea una matriz de identidad de orden 5 (usando np.eye) y luego transforma el tipo en booleano (bool)

In [9]:
i = np.eye(5)
b = i.astype(bool)
print(b)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


Ejercicio 8: Cocatena de forma horizontal (una al costado de la otra) los siguientes arrays

In [10]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

In [11]:
hor = np.concatenate([a1,a2], axis=1)
print(hor)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Ejercicio 9: Cocatena de forma vertical los mismos array

In [12]:
vert = np.concatenate([a1,a2], axis=0)
print(vert)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Ejercicio 9: Crea un array unidimensional que tenga los numeros de 0 a 100 (incluido) con saltos de 2.

In [13]:
a = np.arange(0, (100 + 1), 2)
print(a)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Ejercicio 10: Usando np.where() compara en que elementos el array **a** es mayor al array **b**

In [14]:
a = np.array([1,2,3,4,6])

b = np.array([1,3,2,4,5])

In [15]:
filtro = np.where(a > b)
print(filtro)
print(a[filtro])

(array([2, 4], dtype=int64),)
[3 6]


Ejercicio 11: Genera en un array una secuencia separada de forma equidistante de 5 numeros que van de 0 a 100 (inclusive ambos)

In [16]:
equidist_5 = np.linspace(0, 100, 5)
print(equidist_5)

[  0.  25.  50.  75. 100.]


Ejercicio 12: Crea una matriz de 2x3 con todos los valores igual a 23 (Hint: podes usar [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html) o [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))


In [17]:
a = np.full((2,3),23)
print(a)

[[23 23 23]
 [23 23 23]]


Ejercicio 13: Crea un array de 8x2 numeros aleatorios que sigan la distribucion normal (Hint: [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html))

In [18]:
aleatorio = np.random.normal(size=(8, 2))
print(aleatorio)

[[ 0.88684356 -0.90999067]
 [ 1.64851243 -0.01738413]
 [ 1.03606379 -0.29584957]
 [-0.26377327 -0.25571197]
 [-1.75326733 -1.05738884]
 [ 0.83064857 -0.6263717 ]
 [-0.56055755  0.63956361]
 [-0.20312231 -0.0084568 ]]


Ejercicio 14: Dadas las siguientes matrices, multipliquelas como matrices. Luego multipliquelas como si fueran arrays

In [19]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

In [20]:
m = np.matmul(a,b)
print(m) # u00 = 1*2 + 2*5 + 3*8 = 36
v = a * b
print(v) # u00 = 1*2

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]
[[ 2  6 12]
 [20 30 42]
 [56 72 90]]


Ejercicio 15: Dado el siguiente array, ordenelo de forma ascendente (Hint: [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)). Luego de forma descendente.

In [21]:
 a = np.array([1, 0, 82, 2, 939, 91, 1101, 199, 292, 2, 923, 387, 38, 299])

In [22]:
ind_asc = np.argsort(a)
print(a[ind_asc])

[   0    1    2    2   38   82   91  199  292  299  387  923  939 1101]


In [23]:
ind_des = np.argsort(-a)
print(a[ind_des])

[1101  939  923  387  299  292  199   91   82   38    2    2    1    0]


----

Ejercicio 16: Lee el csv venta_libros en un array. Luego separa las columnas en 3 arrays diferentes, el primero llamado year, el segundo month, y el tercero books

In [24]:
data = np.loadtxt("./datasets/venta_libros.csv", delimiter=",", dtype=int, encoding='utf-8-sig')
print(data)

[[2019    1  106]
 [2019    2  400]
 [2019    3  339]
 [2019    4  389]
 [2019    5  141]
 [2019    6  332]
 [2019    7  386]
 [2019    8  307]
 [2019    9  304]
 [2019   10  167]
 [2019   11  133]
 [2019   12  151]
 [2020    1  276]
 [2020    2   57]
 [2020    3  125]
 [2020    4   27]
 [2020    5  222]
 [2020    6  363]
 [2020    7   26]
 [2020    8  162]
 [2020    9  383]
 [2020   10  383]
 [2020   11  179]
 [2020   12  386]
 [2021    1  432]
 [2021    2  482]
 [2021    3  202]
 [2021    4  115]
 [2021    5  420]
 [2021    6   87]
 [2021    7   36]
 [2021    8  489]
 [2021    9  440]
 [2021   10   83]
 [2021   11  258]
 [2021   12  281]
 [2022    1  393]
 [2022    2  227]
 [2022    3  236]
 [2022    4  453]
 [2022    5  359]
 [2022    6  252]
 [2022    7   57]
 [2022    8  473]
 [2022    9  331]
 [2022   10  349]
 [2022   11  212]
 [2022   12  131]]


In [25]:
year = data[:, 0]
month = data[:, 1]
books = data[:, 2]
print("Year:", year)
print("Month:", month)
print("Books:", books)

Year: [2019 2019 2019 2019 2019 2019 2019 2019 2019 2019 2019 2019 2020 2020
 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 2021 2021 2021 2021
 2021 2021 2021 2021 2021 2021 2021 2021 2022 2022 2022 2022 2022 2022
 2022 2022 2022 2022 2022 2022]
Month: [ 1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  9 10 11 12
  1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  9 10 11 12]
Books: [106 400 339 389 141 332 386 307 304 167 133 151 276  57 125  27 222 363
  26 162 383 383 179 386 432 482 202 115 420  87  36 489 440  83 258 281
 393 227 236 453 359 252  57 473 331 349 212 131]


Usando np.max() obtenga el valor de ventas de libros más alto. Luego, busque a que mes y años corresponde

In [26]:
books_max = np.max(books)
print("Valor de ventas de libros mas alto:", books_max)

Valor de ventas de libros mas alto: 489


In [27]:
ind_books_max = np.argmax(books)
year_books_max = year[ind_books_max]
month_books_max = month[ind_books_max]
print("Corresponde al año:", year_books_max)
print("Corresponde al mes:", month_books_max)

Corresponde al año: 2021
Corresponde al mes: 8


Calcula las ventas totales, las ventas promedio, la mediana de las ventas y el desvio estandar (Hint: [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html))

In [28]:
books_total = np.sum(books)
books_prom = np.mean(books)
books_median = np.median(books)
books_std = np.std(books)
print("Ventas totales:", books_total)
print("Ventas promedio:", books_prom)
print("Mediana de las ventas:", books_median)
print("Desvio estandar:", books_std)

Ventas totales: 12542
Ventas promedio: 261.2916666666667
Mediana de las ventas: 267.0
Desvio estandar: 136.60770450657444
